### PR TITLE
Fix empty input 

### PR DESCRIPTION
**Pull request by ArnavK-09**

### CODE REVIEW

**Comment by ArnavK-09** [comment]
w @Axorax

**Comment by ArnavK-09** [comment]
@Axorax 🗿

**Comment by ArnavK-09** [comment]
@Axorax 💀

**Comment by ArnavK-09** [comment]
@Axorax

**Comment by ArnavK-09** [comment]
> # ~~_**@Axorax **_~~

**Comment by ArnavK-09** [comment]
@Axorax ha

**Comment by Axorax** [comment]
Hey! Sorry for not checking. I have been busy. I recently got dengue for the second time but I'm doing well now.

**Comment by ArnavK-09** [comment]
I'm glad to hear that you're doing well now, despite having dengue for the second time. Health is important, so take care of yourself! thanks for merging 🎉

**Pull request merged**
